# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'LTxCoreDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for LTxCoreDemo
    pod 'LTxCore',:path=>"../"
    
end
